#SD & GJ & VC
class Objects(object):
    
    

    #Images
    #Sword of Oof
    #VC
    def displaySwordOfOof(self):
        print(                    )
        print(                    )
        print( "        /\   "    )
        print( "       /  \  "    )
        print( "      |    | "    )
        print( "      |    | "    )
        print( "      |    | "    )
        print( "      |    | "    )
        print( "      |    | "    )
        print( "      |    | "    )
        print( "      |    | "    )
        print( "      |    | "    )
        print( "      |    | "    )
        print( "      |    | "    )
        print( "      |    | "    )
        print( "      |    | "    )
        print( "  ____|____|____ ")
        print( "  \ ___ OOF___ / ")
        print( "        ()    "   )
        print( "        ()    "   )
        print( "        ()    "   )
        print( "        ()    "   )
        print( "       (  ) "     )
    #VC
    def displayChest(self):
        print("                    ._______________________________. ")
        print("                    ::                             ::")
        print("                    ::                             ::")
        print("                    ::                             ::")
        print("                    ::            _____            :: ")
        print("                    ::===========:  0   : =========::")        
        print("                    |  _________  | : |  __________ |")
        print("                    |    ________  \ /  __________  |")
        print("                    | ___________________________   |")
        print("                    |     ____________________      |")
        print("                    |===============================|")


    def displayShield(self):
       print("          _________________________________  ")
       print("         |  _____________________________  |  ")
       print("         | |                             | | ")
       print("         | |                             | |")
       print("         | |                             | |")
       print("         | |                             | |")
       print("          | |                           | | ")
       print("          | |                           | | ")
       print("          | |                           | | ")
       print("          | |                           | | ")
       print("           | |                         | | ")
       print("            | |                       | | ")
       print("            | |                       | | ")
       print("             | |                     | | ")
       print("              | |                   | | ")
       print("              | |                   | | ")
       print("              | |                   | | ")
       print("               | |                 | | ")
       print("                 | |              | | ")
       print("                   | |          | | ")
       print("                     | |      | | ")
       print("                       | |  | | ")
            
#VC
   def displaySignpost(self):
        print(                                     )
        print(                                     )
        print(     " ____________________________ " )
        print(     "|       ~~~~~~~~~~~~~        |")
        print(     "|         SIGN POST          |")
        print(     "|       ~~~~~~~~~~~~~        |")
        print(     "|    XXX XXXXXXXXXXX XX      |")
        print(     "|     XXXXXXX XXX XXX XX     |")
        print(     "|     XX XXXX XXXXX XXX      |")
        print(     "|____________________________|")
        print(     "             | |              ")
        print(     "             | |              ")
        print(     "             | |              ")
        print(     "             | |              ")
        print(     "             | |              ")
  
    
    def displayCodexMaterials(self):
        print(":-------------------------|")
        print(":        Materials        |")
        print(":       ~~~~~~~~~~~       |")
        print(":                         |")
        print(":        Ratio 1:1        |")
        print(": Iron: 25g     Dust: 25g |")
        print(": Iron: 1000g Dust: 1000g |")
        print(": Iron: 5000g Dust: 5000g |")
        print(":                         |")
        print(":                         |")
        print(":                         |")
        print(":                         |")
        print(":                         |")
        print(":                         |")
        print(":                         |")
        print(":                         |")
        print(":                         |")
        print(":                         |")
        print(":                         |")
        print(":                         |")
        print(":                         |")
        print(":-------------------------|")
        
    def displayExplosion(self):
        print("      _.-^^---....,,__         ")
        print("  _--                  --_     ")
        print(" <                        >)   ")
        print(" |                         |   ")
        print("  \._                   _./    ")
        print("     ```--. . , ; .--'''       ")
        print("           | |   |             ")
        print("        .-=||  | |=-.          ")
        print("        `-=#$%&%$#=-'          ")
        print("           | ;  :|             ")
        print("  _____.,-#%&$@%#&#~,._____    ")
