#SD & GJ
class Objects(object):
    

    #Images
    #Sword of Oof
    def displaySwordOfOof(self):
        print(                    )
        print(                    )
        print( "        /\   "    )
        print( "       /  \  "    )
        print( "      |    | "    )
        print( "      |    | "    )
        print( "      |    | "    )
        print( "      |    | "    )
        print( "      |    | "    )
        print( "      |    | "    )
        print( "      |    | "    )
        print( "      |    | "    )
        print( "      |    | "    )
        print( "      |    | "    )
        print( "      |    | "    )
        print( "      |    | "    )
        print( "  ____|____|____ ")
        print( "  \ ___ OOF___ / ")
        print( "        ()    "   )
        print( "        ()    "   )
        print( "        ()    "   )
        print( "        ()    "   )
        print( "       (  ) "     )

    def displayCodexMaterials(self):
        print(":-------------------------|")
        print(":        Materials        |")
        print(":       ~~~~~~~~~~~       |")
        print(":                         |")
        print(":        Ratio 1:1        |")
        print(": Iron: 25g     Dust: 25g |")
        print(": Iron: 1000g Dust: 1000g |")
        print(": Iron: 5000g Dust: 5000g |")
        print(":                         |")
        print(":                         |")
        print(":                         |")
        print(":                         |")
        print(":                         |")
        print(":                         |")
        print(":                         |")
        print(":                         |")
        print(":                         |")
        print(":                         |")
        print(":                         |")
        print(":                         |")
        print(":                         |")
        print(":-------------------------|")
